version: '3'
services:
  sfl-api:
    build: .
    container_name: sfl-api
    volumes:
      - .:/home/app
    external_links:
      - actionmedia
    ports:
      - 5001:5001
    environment:
      - BRANCH=dev
      - VIRTUAL_HOST=sfl-api-local.surge.systems
    networks:
      - proxy
      - database
    depends_on:
      - redis

  redis:
    image: redis:latest

networks:
  database:
    external: true
  proxy:
    external: true
  default:
    external:
      name: actionmedia-network
